---
- hosts: all
  gather_facts: no
  tasks:


  - shell: /usr/bin/uptime
    register: result

  - debug:
    var: result

  - debug:
    # var: hostvars[inventory_hostname]
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
