---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: get root ssh DO ID
      become: yes
      shell: cat /root/.ssh/do_id
      register: ssh_id

    - name: get DOTOKEN
      become: yes
      shell: cat /home/DOTOKEN
      register: DOTOKEN

    - name: get jenkins ssh DO ID
      become: yes
      shell: cat /var/lib/jenkins/.ssh/do_id
      register: ssh_jenkins_id

    - name: check if dropletID exists
      become: yes
      stat: 
        path: /home/checkboxCanary/dropletID
      register: droplet_exists

    - name: get dropletID if exists
      become: yes
      shell: cat /home/checkboxCanary/dropletID
      register: dropletID
      when: droplet_exists.stat.exists == True

    - name: delete current stable droplet
      digital_ocean:
        state: absent
        command: droplet
        id: "{{ dropletID.stdout }}"
        wait_timeout: 500
        api_token: "{{ DOTOKEN.stdout }}"
      when: droplet_exists.stat.exists == True


    - name: create new canary droplet
      digital_ocean:
        state: present
        command: droplet
        name: canary
        size_id: 512mb
        region_id: nyc1
        image_id: ubuntu-14-04-x64
        wait_timeout: 500
        ssh_key_ids: "{{ ssh_id.stdout }},{{ ssh_jenkins_id.stdout }}"
        api_token: "{{ DOTOKEN.stdout }}"
      register: new_droplet

    - name: delete dropletID file
      file:
        path: /home/checkboxCanary/dropletID
        state: absent

    - name: make dropletID file present
      file:
        path: /home/checkboxCanary/dropletID
        state: touch
        mode: 0777

    - name: set dropletID file
      lineinfile:
        path: /home/checkboxCanary/dropletID
        line: "{{ new_droplet.droplet.id }}"

    - name: make inventory file absent
      file:
        path: /home/checkboxCanary/canaryInventory
        state: absent

    - name: make inventory file present
      file:
        path: /home/checkboxCanary/canaryInventory
        state: touch
        mode: 0777

    - name: set inventory file
      lineinfile:
        path: /home/checkboxCanary/canaryInventory
        line: "[nodes]\n{{ new_droplet.droplet.ip_address }} ansible_ssh_user=root"

    # - name: add to known hosts
    #   become: jenkins
    #   #shell: "ssh-keyscan -H {{ new_droplet.droplet.ip_address }} >> ~/.ssh/known_hosts"
    #   shell: "ssh-keyscan -H {{ new_droplet.droplet.ip_address }} >> /var/lib/jenkins/.ssh/known_hosts"

    # - name: add to known hosts
    #   known_hosts:
    #     name: "{{ new_droplet.droplet.ip_address }}"
    #     state: present
    #     key: 
    #   tags:
    #     - test

    - name: make IP file absent
      file:
        path: /home/CANARYIP
        state: absent

    - name: make IP file present
      file:
        path: /home/CANARYIP
        state: touch
        mode: 0777

    - name: set IP file
      lineinfile:
        path: /home/CANARYIP
        line: "{{ new_droplet.droplet.ip_address }}"

    - debug:
        msg: "canary IP: {{ new_droplet.droplet.ip_address }}"

    - name: Wait for SSH to come up
      local_action: wait_for host={{ new_droplet.droplet.ip_address }} port=22 delay=60 timeout=320 state=started