---

#Install Mysql and configure

#Makesure python is installed


- name: Install mysql-server and python-mysqldb from the internet.
  apt:
   name: "{{item}}" #deb: https://dev.mysql.com/get/mysql-apt-config_0.8.7-1_all.deb
   update_cache: yes
   state: present
  become: yes
  with_items:
    - mysql-server
    - mysql-client
    - python-dev
    - python-pip
    - gcc
    - libmysqlclient-dev
    - python-setuptools
    - python-mysqldb
    - git-core


- name: copy .my.cnf file with root password credentials
  # template: src=templates/.my.cnf dest=/home/vagrant/.my.cnf owner=root mode=0644
  template: src=templates/my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0644
  become: yes

- name: Start the MySQL service
  become: yes
  service:
    name: mysql
    state: started
    enabled: true    #started at boot time

- name: remove the test database
  become: yes
  mysql_db:
    config_file: /etc/mysql/my.cnf
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_client_password }}"

- name: update mysql root password for root accounts
  become: yes
  mysql_user:
    config_file: /etc/mysql/my.cnf
    name: root
    host: localhost
    password: "{{ mysql_client_password }}"
    login_user: root
    login_password: "{{ mysql_client_password }}"
    check_implicit_admin: yes
    state: present

- name: update mysql root password for ALL root accounts
  become: yes
  mysql_user:
    config_file: /etc/mysql/my.cnf
    name: root
    host: "{{ item }}"
    password: "{{ mysql_client_password }}"
    login_user: root
    login_password: "{{ mysql_client_password }}"
    check_implicit_admin: yes
  with_items:
    - localhost
    - ::1
    - %

- name: ensure no anon users in DB
  become: yes
  mysql_user:
    config_file: /etc/mysql/my.cnf
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ inventory_hostname }}"
    - localhost
    - ::1

- name: Restarting mysql service
  become: yes
  service:
    name: mysql
    state: restarted
