---

- hosts: control
  gather_facts: no
  tasks:

  - name: Install python
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts: control

  vars:
    inventory_file_name: ../inventory.vagrant
    harness_directory: "{{ ansible_env.HOME }}/harness"

  tasks:

  - name: Create droplets 
    shell: ls

  - name: Add Ansible Repo
    become: yes
    apt_repository: repo=ppa:ansible/ansible

  - name: Install APT Packages
    become: yes
    apt: name={{ item }} update_cache=yes
    with_items:
    - software-properties-common
    - zip
    - unzip
    - python-pip
    - python-netaddr
    - ansible
    - build-essential 
    - libssl-dev 
    - libffi-dev 
    - python-dev

  - name: Upgrade setup tools
    become: yes
    shell: pip install --upgrade setuptools


  - name: Install Cryptography for Vault Performance
    become: yes
    pip: name=cryptography

  - name: Create Harness Directories
    file: path={{ item }} state=directory
    with_items:
    - "{{ harness_directory }}"
    - "{{ harness_directory }}/playbooks"
    - "{{ harness_directory }}/playbooks/templates"

  - name: Copy Ansible Files
    copy: src={{ item.src }} dest={{ harness_directory }}/{{ item.dest }} mode=777
    with_items:
    - src:  templates
      dest: playbooks/
    - src:  bootstrap-cluster.yml
      dest: playbooks/bootstrap-cluster.yml
    - src:  install-nomad.yml
      dest: playbooks/install-nomad.yml
    - src:  requirements.yml
      dest: playbooks/requirements.yml
    - src:  vars.yml
      dest: playbooks/vars.yml
    - src:  "{{ inventory_file_name }}"
      dest: inventory
    - src:  ../ansible.cfg
      dest: ansible.cfg
    - src: ~/.ssh/ocean
      dest: ocean
    - src:  stableSetup.yml
      dest: playbooks/stableSetup.yml
    - src:  main.yml
      dest: playbooks/main.yml
    - src:  configure_redis.yml
      dest: playbooks/configure_redis.yml
    tags:
      - test

  - name: Install Roles
    command: ansible-galaxy install -r {{ harness_directory }}/playbooks/requirements.yml